name: Lint

on:
  workflow_dispatch:
  push:
    # trigger only on main branch
    branches:
      - main
    # trigger only on changes to the following files
    paths:
      - "pystreams/src/**"
      - "pystreams/tests/**"
      - ".github/workflows/test-docker.yaml"
  pull_request:
    # trigger only on main branch
    branches:
      - main
    # trigger only on changes to the following files
    paths:
      - "pystreams/src/**"
      - "pystreams/tests/**"
      - ".github/workflows/test-docker.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          src: "./pystreams"
