name: Multiplatform tests

on:
  workflow_dispatch:
  push:
    # trigger only on main branch
    branches:
      - main
    # trigger only on changes to the following files
    paths:
      - "pystreams/src/**"
      - "pystreams/tests/**"
      - "pystreams/poetry.lock"
      - "pystreams/pyproject.toml"
      - "environment.yaml"
      - "requirements.txt"
      - ".github/workflows/test-multiplatform.yaml"
  pull_request:
    # trigger only on main branch
    branches:
      - main
    # trigger only on changes to the following files
    paths:
      - "pystreams/src/**"
      - "pystreams/tests/**"
      - "pystreams/poetry.lock"
      - "pystreams/pyproject.toml"
      - "environment.yaml"
      - "requirements.txt"
      - ".github/workflows/test-multiplatform.yaml"

# env for all jobs
env:
  CONDA_CACHE_DIR: ~/conda_pkgs_dir
  POETRY_CACHE_DIR: ~/.cache/pypoetry
  PIP_CACHE_DIR: ~/.cache/pip
  # increase this value to manually reset cache
  CACHE_NUMBER: 0

jobs:
  test:
    name: Run tests
    strategy:
      # don't stop all tests if one fails
      fail-fast: false
      matrix:
        # better to use pinned versions here
        config:
          - { os: ubuntu-latest, shell: bash -l }
          - { os: macos-latest, shell: bash -l }
          - { os: windows-latest, shell: cmd /C CALL }
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        # necessary for conda to work
        shell: ${{ matrix.config.shell }} {0}
    steps:
      - # get repository code
        name: Checkout code
        uses: actions/checkout@v3
      - # get conda, poetry and pip cache (persistent between runs)
        name: Cache packages
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.CONDA_CACHE_DIR }}
            ${{ env.POETRY_CACHE_DIR }}
            ${{ env.PIP_CACHE_DIR }}
          key: ${{ runner.os }}-pkgs-${{ env.CACHE_NUMBER }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"
      - name: Set up pip cache
        run: python3 -m pip config set global.cache-dir ${{ env.PIP_CACHE_DIR }}
      - name: Install poetry
        run: python3 -m pip install -r requirements.txt
      - name: Set up poetry cache
        run: poetry config cache-dir ${{ env.POETRY_CACHE_DIR }}
      - # create and activate conda environment
        name: Set up environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pystreams
          environment-file: environment.yaml
          # necessary for caching to work
          use-only-tar-bz2: true
      - # install only dependencies
        name: Install dependencies
        working-directory: pystreams
        run: poetry install --no-root --only main,test
      - # workaround for non-editable install, waiting for https://github.com/python-poetry/poetry/issues/1382
        name: Build package
        working-directory: pystreams
        run: poetry build -f wheel
      - # use pip to install wheel produced in previous step
        name: Install package
        working-directory: pystreams
        # python from conda should be called just by 'python', not 'python3'
        run: python -m pip install --no-deps --no-index --no-cache-dir --find-links=dist pystreams[test]
      - name: Run tests
        run: pytest pystreams
